### ISSUE TITLE
Typescript React

### ISSUE THREAD

**Issue by ovidius72** [luxcium/pop-n-lock-theme-vscode#16]
Thanks for this great theme. I really enjoy using it but it seems that typescript react (.tsx) files are not supported. No syntax.
Can you please add it ?
Thanks

**Comment by luxcium** [comment]
ok great I will look into it right now

**Comment by luxcium** [comment]
@ovidius72  Tanks for the update I think it should be all working now please let me know if something is still wrong by opening a new issue #21  should have fixed all the problems ... please make sure it has been updated in your VSCode to version 3.9.2 or above ...
