### ISSUE TITLE
Unused variables not greying out properly

### ISSUE THREAD

**Issue by dhruv-jain-snaphunt** [Luxcium/pop-n-lock-theme-vscode#26]
Hi, I installed this theme but had to reinstall vscode on my mac and after reinstalling, the unused variable greying out doesn't seem to work properly. I'm using the recommended settings and the language type is Babel Javascript. Any advice on what might be causing this or how I can debug?

**Comment by Luxcium** [comment]
Ok thanks for pointing that issue to our attention we will fix the issue promptly.

**Comment by dhruv-jain-snaphunt** [comment]
Yup sure! Let me know if you need any further information

**Comment by Luxcium** [comment]
Unused source code:

editorUnnecessaryCode.border: Border color of unnecessary (unused) source code in the editor.
editorUnnecessaryCode.opacity: Opacity of unnecessary (unused) source code in the editor. For example, "#000000c0" will render the code with 75% opacity. For high contrast themes, use the "editorUnnecessaryCode.border" theme color to underline unnecessary code instead of fading it out.

**Comment by Luxcium** [comment]
Theses are the values used :
    "editorUnnecessaryCode.border": "#95B4",
    "editorUnnecessaryCode.opacity": "#FFF5",

are you sure you have set the option in your settings to :   "editor.showUnused": true

**Comment by Luxcium** [comment]
VS Code ships with built-in support for fading out unused locals/parameters/imports in JavaScript and TypeScript. You can enable/disable this feature by setting:

```json
// For all languages (it is enabled the default)
"editor.showUnused": true

// Or just for a specific language
"[typescript]": {
   "editor.showUnused": true
}
```
Extensions can also add support for other languages.

You can additionally mark unused variables as warnings by setting noUnusedLocals and/or noUnusedParameters in your jsconfig or tsconfig:

```json
{
  "compilerOptions": {
    "noUnusedLocals": true,
    "noUnusedParameters": true
  },
  "exclude": [
    "node_modules",
    "**/node_modules"
  ]
}
```
This adds a squiggly and error for unused variables in addition to graying them out

**Comment by dhruv-jain-snaphunt** [comment]
```
{
  "editor.formatOnSave": true,
  "gitlens.views.repositories.location": "scm",
  "gitlens.views.fileHistory.location": "scm",
  "gitlens.views.lineHistory.location": "scm",
  "gitlens.views.compare.location": "scm",
  "gitlens.views.search.location": "scm",
  "terminal.external.osxExec": "iTerm.app",
  "terminal.integrated.fontFamily": "Fira Mono for Powerline",
  "editor.showUnused": true,
  "terminal.integrated.fontSize": 14,
  "workbench.iconTheme": "material-icon-theme",
  "workbench.colorTheme": "Pop N' Lock Theme by Luxcium ✨",
  "files.encoding": "utf8",
  "files.autoGuessEncoding": false,
  "workbench.editor.highlightModifiedTabs": true,
  "material-icon-theme.showReloadMessage": true,
  "editor.fontFamily": "Fira Code iScript, Fira Code",
  "editor.fontLigatures": true,
  "editor.fontSize": 16,
  "editor.suggestFontSize": 16
}
```
This is my settings.json file right now - VSCode doesn't seem to support the following settings:

```
"editorUnnecessaryCode.border": "#95B4",
"editorUnnecessaryCode.opacity": "#FFF5",
```

**Comment by Luxcium** [comment]
> This is my settings.json file right now - VSCode doesn't seem to support the following settings:
> 
> ```
> "editorUnnecessaryCode.border": "#95B4",
> "editorUnnecessaryCode.opacity": "#FFF5",
> ```

No these are the setting used inside the theme to configure it uses only the last value (here `4` or `5`) to determine the opacity …

**Comment by Luxcium** [comment]
should have been fixed let me know if probleme persist
