### ISSUE TITLE
Allow for theme only installation

### ISSUE THREAD

**Issue by djensen47** [Luxcium/pop-n-lock-theme-vscode#28]
I installed this theme and not paying attention, I realized it also installed a bunch of other extensions that I may or may not have wanted on my system.

It would be wonderful if you could provide a version of the theme that does _not_ include all of the other extensions.

Thanks.

**Comment by Luxcium** [comment]
Ok tanks for pointing that out until this issue is review and fixed you can disable the features you don’t want.

**Comment by Luxcium** [comment]
Can you possibly tell us what is the most important thing for you to be removed we might decide to remove none, some or all included extension but it could be helpful if you let us know what feature or extension is the most irritating to you ...

[x] alphabetical-sorter
[x] better-comments
[x] bracket-pair-colorizer-2
[x] material-icon-theme

**Comment by djensen47** [comment]
All of the above. I realize that if I looked carefully then I would have seen that a bunch of extensions are included when I installed but I missed it. Suddenly I had all of this extra behavior in my IDE that I wasn't expecting and that I don't want.

I would propose
- Pop N Lock Deluxe (all the extensions)
- Pop N Lock Lite (none of the extensions)

**Comment by Luxcium** [comment]
I have removed [ ] alphabetical-sorter in the latest version but you can disable the extensions if you want to continue using the theme without the other extensions
[x] better-comments
[x] bracket-pair-colorizer-2
[x] material-icon-theme
