### ISSUE TITLE
Increase opacity of hover popovers

### ISSUE THREAD

**Issue by FadeZhanger** [Luxcium/pop-n-lock-theme-vscode#32]
Hey! Thanks for making this theme, love using it! 

My only issue is that the hover popovers are slightly too transparent, which decreases readability, particularly with the debug popovers:

![image](https://user-images.githubusercontent.com/30360288/61178069-fa15b880-a5b2-11e9-9578-23eb2ae7aecb.png)

In my opinion, the popover text blends too much with the background text. What do you think?

**Comment by Luxcium** [comment]
should have been fixed with #33 by @Luxcium
please open a new issue with more details if the problem persists! 

Thanks to @FadeZhanger
