### ISSUE TITLE
Bold text as in example?

### ISSUE THREAD

**Issue by h-h-h-h** [Luxcium/pop-n-lock-theme-vscode#40]
Here are two slides for your theme: https://vscodethemes.com/e/Luxcium.pop-n-lock-theme-vscode.

One of the slides has method calls in bold. So, I assumed there would have to be a setting for that. But on [the extension page](https://marketplace.visualstudio.com/items?itemName=Luxcium.pop-n-lock-theme-vscode), I didn't find anything.

So: How can I get this bold text? And could that be better documented, please?

**Comment by Luxcium** [comment]
I was trying to look into it (not there is no option to toggle that) but interestingly enough the code is not bold but the mouseover code example wa ... 
<img width="1206" alt="Capture d’écran, le 2019-09-20 à 11 51 47" src="https://user-images.githubusercontent.com/42672814/65340841-19c1f200-db9d-11e9-9fee-3131e492f22e.png">

**Comment by Luxcium** [comment]
Its supported in typescript and it will be fixed in the next update ... 

<img width="687" alt="Capture d’écran, le 2019-09-20 à 11 54 48" src="https://user-images.githubusercontent.com/42672814/65341049-7f15e300-db9d-11e9-8d9b-8e4753651383.png">

**Comment by Luxcium** [comment]
SO there was no documentation because it's not a modifiable feature ...

**Comment by Luxcium** [comment]
<img width="584" alt="Capture d’écran, le 2019-10-26 à 09 13 17" src="https://user-images.githubusercontent.com/42672814/67620078-f9efa080-f7d0-11e9-8d5e-90a12d5e3e68.png">
