### ISSUE TITLE
States of toggle buttons of search function barely distinguishable

### ISSUE THREAD

**Issue by h-h-h-h** [Luxcium/pop-n-lock-theme-vscode#41]
## States of the toggle buttons

Imagine the images as small as the real GUI.

Nothing pressed or focused:

![basic state](https://user-images.githubusercontent.com/13482553/65209084-4986d200-da97-11e9-97a0-4e98f5479df0.png)

First one **focused** and **not pressed**:

![focused](https://user-images.githubusercontent.com/13482553/65209085-4a1f6880-da97-11e9-9b94-4bc1d3d881be.png)

First one **focused** and **pressed**:

![focused and pressed](https://user-images.githubusercontent.com/13482553/65209086-4a1f6880-da97-11e9-948b-09e267714def.png)

First one **not focused** and **pressed**:

![pressed](https://user-images.githubusercontent.com/13482553/65209087-4a1f6880-da97-11e9-8c21-ad57c1d70394.png)

## Problems

When using the mouse to toggle the buttons, it's hard to intuitively understand what state the buttons are currently in.

When using <kbd>Tab</kbd> and <kbd>Space</kbd>, the focused-only state looks much too similar to the pressed state.

---

It's the same with the vertical multi-file search tool. Also, there, the background color of the textboxes look too bright. That background color could be darker in both search tools, I think.

**Comment by Luxcium** [comment]
I am looking into it tanks for the proposition. I agree with you I had the same problem will place this issue on my priority list ...

**Comment by Luxcium** [comment]
<img width="517" alt="Capture d’écran, le 2019-10-26 à 08 58 48" src="https://user-images.githubusercontent.com/42672814/67619881-eba08500-f7ce-11e9-9c0b-1b177218808d.png">

**Comment by Luxcium** [comment]
I don't have any selectors to change the focus/unfocused color states if you know of a theme that is doing it let me know and I will investigate further ...
