### ISSUE TITLE
Inline comments aren't easy on the eye. Line comments are a bit dim.

### ISSUE THREAD

**Issue by h-h-h-h** [Luxcium/pop-n-lock-theme-vscode#42]
Inline comments in JavaScript in the style `/*...*/` look like black light:

![code](https://user-images.githubusercontent.com/13482553/65210328-1b0af600-da9b-11e9-846b-abf340ca3a76.png)

**Comment by Luxcium** [comment]
I am looking into it tanks for the proposition

**Comment by Luxcium** [comment]
@h-h-h-h When the next version will have been published tell me if the PR #46 fixes the issue or feel free to open a new issue if anything is not perfect for you 😄

**Comment by h-h-h-h** [comment]
(Also referring to images and issue [here](https://github.com/Luxcium/pop-n-lock-theme-vscode/issues/43#issuecomment-546584316).)

Unfortunately, inline comments still look like black light. I deem comments to be much more important than to display them in a barely visible, barely readable manner. :/

The delimiters `/*...*/` are now barely visible at all.

Maybe a more reddish and lighter shade of violet like [`#b265ff`](https://html-color.codes/hex/b265ff) would be better. I'm also not so sure about the necessity of a huge difference in color between line and inline comments. If you agree, inline comments could get the line comments color and both could be made a bit lighter.

**Comment by Luxcium** [comment]
<img width="977" alt="Capture d’écran, le 2019-10-26 à 07 44 07" src="https://user-images.githubusercontent.com/42672814/67619093-2c939c00-f7c5-11e9-9ddd-73b606a2b2e9.png">

**Comment by Luxcium** [comment]
**Final revision:**
please open a new ticket if it is not working correcly 
<img width="986" alt="Capture d’écran, le 2019-10-26 à 07 55 16" src="https://user-images.githubusercontent.com/42672814/67619158-2d78fd80-f7c6-11e9-808c-cb4ca90e6d10.png">

**Comment by Luxcium** [comment]
based on [`#44AADD`](https://html-color.codes/hex/44aadd) 
and based on [`#AA44DD`](https://html-color.codes/hex/44aadd) 

<img width="599" alt="Capture d’écran, le 2019-10-26 à 08 04 54" src="https://user-images.githubusercontent.com/42672814/67619259-649bde80-f7c7-11e9-8400-600ce1f6fcad.png">

**Comment by h-h-h-h** [comment]
Thank you! I'm glad the delimiter thing is possible.

<sup>I'm just leaving [this link to proof of other supporters](https://stackoverflow.com/questions/52174690/change-color-of-characters-surrounding-comments-in-vs-code) for possible future reference.</sup>
