### ISSUE TITLE
Please dim down delimiters of inline comments

### ISSUE THREAD

**Issue by h-h-h-h** [Luxcium/pop-n-lock-theme-vscode#43]
The color of the delimiters of inline comments like `/*...*/` in JavaScript should be mixed with the background a bit to emphasize the actual comment text.

I hope this is possible.

Mockup (effect could be increased, perhaps):

![mockup](https://user-images.githubusercontent.com/13482553/65211175-109e2b80-da9e-11e9-852f-f0949315a271.png)

**Comment by Luxcium** [comment]
@h-h-h-h  this is how it should look ...
Font is set to extra bold to show the changes ...

<img width="991" alt="Capture d’écran, le 2019-10-26 à 04 50 51" src="https://user-images.githubusercontent.com/42672814/67616966-63a98380-f7ac-11e9-88f6-927f29a0cab4.png">

**Comment by Luxcium** [comment]
This one is with the suggested front setting of the project with a window zoom level of 2

  "workbench.colorTheme": "Pop N' Lock Theme by Luxcium ✨",
  "editor.fontFamily": "Fira Code iScript, Fira Code",
  "editor.fontSize": 17,
  "window.zoomLevel": 2,

<img width="1030" alt="Capture d’écran, le 2019-10-26 à 04 51 22" src="https://user-images.githubusercontent.com/42672814/67616978-8f2c6e00-f7ac-11e9-98dc-26fc6ad405d3.png">

**Comment by Luxcium** [comment]
**Final revision:**
please open a new ticket if it is not working correcly 
<img width="986" alt="Capture d’écran, le 2019-10-26 à 07 55 16" src="https://user-images.githubusercontent.com/42672814/67619158-2d78fd80-f7c6-11e9-808c-cb4ca90e6d10.png">

**Comment by Luxcium** [comment]
based on [`#44AADD`](https://html-color.codes/hex/44aadd) 
and based on [`#AA44DD`](https://html-color.codes/hex/44aadd) 

<img width="599" alt="Capture d’écran, le 2019-10-26 à 08 04 54" src="https://user-images.githubusercontent.com/42672814/67619259-649bde80-f7c7-11e9-8400-600ce1f6fcad.png">
