### ISSUE TITLE
Option to disable italic font styles

### ISSUE THREAD

**Issue by yellow-pumpkin** [Luxcium/pop-n-lock-theme-vscode#44]
Hello!

First of all, thank you for this theme. It's so wonderful.

Personally, I really dislike italic fonts when programming. I know I'm a minority here, and I'm sorry for asking. But I find italic font styles distracting, and I would like to turn them off completely. I know I can do it manually by setting custom editor.tokenColorCustomizations values in my settings file. However, due to the extensive use of italic font styles throughout the theme, that would take a long time.

Is it possible to maybe offer an option to disable all italic font styles in the theme? (Again, I'm sorry for asking. Nobody else wants this I guess.)

Thanks!

**Comment by the2199** [comment]
I second that

**Comment by the2199** [comment]
i was able to remove the  italic font 
here is the link of the modified Extension
[https://filebin.net/fu42qjrgr0tciuz3](url)
or 
[https://ufile.io/ghpz1mqp](url)
