### ISSUE TITLE
The difference between the color of numbers and color of the units is not big enough

### ISSUE THREAD

**Issue by black-black-cat** [Luxcium/pop-n-lock-theme-vscode#45]
Hey buddy. Thanks for your great theme.

The difference between the color of the number and the color of the unit, like `px`, is not big enough in css syntax.

![Code_E5yMMW7LCb](https://user-images.githubusercontent.com/15521864/67173854-a6f1a400-f3f2-11e9-991b-f9b8627133a6.png)

**Comment by Luxcium** [comment]
do you have a suggested or prefered colour?

**Comment by black-black-cat** [comment]
FYI @Luxcium 
The color of unit in other syntax is `#eeddaadd`: 
![1571708065(1)](https://user-images.githubusercontent.com/15521864/67254436-96ebca00-f4af-11e9-8df4-3ea054978dcd.png)

And I also like the color of unit to be the green one like `#ccee55cc`.

**Comment by Luxcium** [comment]
<img width="425" alt="Capture d’écran, le 2019-10-26 à 09 41 33" src="https://user-images.githubusercontent.com/42672814/67620436-d0387880-f7d4-11e9-94cc-443fe6f4c97a.png">
