### ISSUE TITLE
v3.18.5 doesn't work at all

### ISSUE THREAD

**Issue by h-h-h-h** [Luxcium/pop-n-lock-theme-vscode#48]
After updating and restarting the editor,

- the theme doesn't work (falls back on default);
- the extension is grayed out under "EXTENSIONS: INSTALLED";
- the tabbed extension page has no button "Set Color Theme" (only "Uninstall");
- the theme isn't in the list when you do: Ctrl+P, `> Preferences: Color Theme` (also wasn't the case previously).

Currently, I must downgrade to v3.18.4 for the extension to work.

**Comment by h-h-h-h** [comment]
**Editor info from "About" dialog:**

Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by Luxcium** [comment]
Next/version Luxcium.pop-n-lock-theme-vscode@3.18.6 #49 should be fixing this issue
