### ISSUE TITLE
Better Comments config options

### ISSUE THREAD

**Issue by noltron000** [Luxcium/pop-n-lock-theme-vscode#59]
Hey there, Luxcium! I ❤️ love using your theme; its got a ✨ certain pazzaz that the others just don't got.

I'm posting this issue because of **better comments**. I like what the extension is going for, but I don't like the default config. I was wondering if you have configs for **better comments** that you use with this theme? 

If so, I was wondering if it could be somehow included with the theme...or in the readme, maybe? If not, maybe its something you would consider adding?

Either way...your project is much appreciated!

**Comment by Luxcium** [comment]
My configs have not been edited with the idea of being published but I am doing a copy-paste just for you I don't know if it could be helpful and they have not been reviewed for optimal coloration so I will keep this issue open until I can figure out if I can provide a better response (answer) to your request ... 

[<img width="923" alt="Capture d’écran, le 2019-12-09 à 07 32 54" src="https://user-images.githubusercontent.com/42672814/70435961-33652e00-1a56-11ea-8d24-1cd263bd9388.png">](https://github.com/Luxcium/my-zsh/blob/ffd4c297c84701841e524144362968cdeb0de0e4/luxcium/.aliases.sh#L1)
[Link to this code](https://github.com/Luxcium/my-zsh/blob/ffd4c297c84701841e524144362968cdeb0de0e4/luxcium/.aliases.sh#L1)
```JSON
{
"better-comments.tags": [
    {
      "tag": "!!",
      "color": "#FF2D00",
      "strikethrough": false,
      "backgroundColor": "transparent"
    },
    {
      "tag": "?",
      "color": "#3498DB",
      "strikethrough": false,
      "backgroundColor": "transparent"
    },
    {
      "tag": "$",
      "color": "#f48e41",
      "strikethrough": false,
      "backgroundColor": "transparent"
    },
    {
      "tag": "#",
      "color": "#4AE",
      "strikethrough": false,
      "backgroundColor": "transparent"
    },
    {
      "tag": "%",
      "color": "#41e2f4",
      "strikethrough": false,
      "backgroundColor": "transparent"
    },
    {
      "tag": "+",
      "color": "#c5f442",
      "strikethrough": false,
      "backgroundColor": "transparent"
    },
    {
      "tag": "&",
      "color": "#a041f4",
      "strikethrough": false,
      "backgroundColor": "transparent"
    },
    {
      "tag": "//",
      "color": "#6d6060",
      "strikethrough": false,
      "backgroundColor": "transparent"
    },
    {
      "tag": "todo",
      "color": "#FF8C00",
      "strikethrough": false,
      "backgroundColor": "transparent"
    },
    {
      "tag": "*",
      "color": "#98C379",
      "strikethrough": false,
      "backgroundColor": "transparent"
    },
    {
      "tag": "¬",
      "color": "#ffa0a0",
      "strikethrough": false,
      "backgroundColor": "transparent"
    }
  ]
}
```

**Comment by Luxcium** [comment]
the code in the image above display information related to a different project but Pop N' Lock Theme by Luxcium ✨ has [an MIT License](https://github.com/Luxcium/pop-n-lock-theme-vscode/blob/3fe74429d33fe7c856de22691d5eec5004e5c7ef/LICENSE)

**Comment by noltron000** [comment]
Thanks for that, its appreciated. I'm going to stay subscribed to this post in case you ever get around to it. Otherwise its no biggie; I will still keep using your theme either way!

**Comment by Luxcium** [comment]
one way of doing it is to go in command pallet and type `Inspect Tokens` to be able to get the color code of a specific token and using this in your configuration to match the theme or use theses colors 

<img width="172" alt="Capture d’écran, le 2020-03-29 à 04 28 56" src="https://user-images.githubusercontent.com/42672814/77844599-e082c400-7175-11ea-9029-a5edc0b7fb7a.png">

```json
  /*
    //   "#F15F",
    //   "#FB3F",
    //   "#4AEF",
    //   "#BD2F",
  */
```

<img width="911" alt="Capture d’écran, le 2020-03-24 à 03 45 35" src="https://user-images.githubusercontent.com/42672814/77844382-64d44780-7174-11ea-9e5b-0d0d83a5c2e9.png">

**Comment by Luxcium** [comment]
I also have set rulers it might be at the maximum number of col and above I use 80

<img width="933" alt="Capture d’écran, le 2020-03-29 à 04 26 41" src="https://user-images.githubusercontent.com/42672814/77844554-a5809080-7175-11ea-92c9-979e4d94ba36.png">

```json
"editor.rulers": [
    {
      "column": 2,
      "color": "#FA06"
    },
    {
      "column": 80,
      "color": "#FA0E"
    },
    {
      "column": 81,
      "color": "#F15F"
    },
    {
      "column": 84,
      "color": "#4AE4"
    },
    {
      "column": 88,
      "color": "#4AE6"
    },
    {
      "column": 93,
      "color": "#4AE8"
    }
]
```

**Comment by noltron000** [comment]
Hey, thanks for the info! Being able to get the color codes of particular items or _tokens_ is pretty cool. I'll be sure to use this feature.
