### ISSUE TITLE
Support Javascript/Typescript semantic highlighting

### ISSUE THREAD

**Issue by DanielHZhang** [Luxcium/pop-n-lock-theme-vscode#62]
With the VSCode February 2020 update (v1.43), [semantic highlighting](https://code.visualstudio.com/updates/v1_43#_typescript-semantic-highlighting) was introduced. It is enabled by default (or with `"editor.semanticHighlighting.enabled": true`). 

With semantic highlighting enabled, a lot of the unique context colors have been reduced to a single color, causing the overall highlighting to look much worse.

**With semantic highlighting enabled:**
![image](https://user-images.githubusercontent.com/30360288/76580794-8f04e480-64a7-11ea-889d-901891d4d835.png)

**Without semantic highlighting:**
![image](https://user-images.githubusercontent.com/30360288/76580689-3afa0000-64a7-11ea-83c7-ebc66caeaca5.png)

**Comment by Luxcium** [comment]
I am aware of this issue and working on the situation right now ...  This feature help fixin' a lot of problems I had to fix by clever workarounds ... wich are broken now if using that feature ...

**Comment by Luxcium** [comment]
https://github.com/microsoft/vscode/pull/92737 fixed it 
more Infos: https://github.com/microsoft/vscode/pull/92737#issue-388820821 
<img width="1920" alt="Capture d’écran, le 2020-06-03 à 05 44 07" src="https://user-images.githubusercontent.com/42672814/83622548-24bb8780-a55e-11ea-8ad1-15c527969eaa.png">
<img width="1920" alt="Capture d’écran, le 2020-06-03 à 05 44 59" src="https://user-images.githubusercontent.com/42672814/83622550-24bb8780-a55e-11ea-90df-61900a85107a.png">
