### ISSUE TITLE
Reduce transparency option

### ISSUE THREAD

**Issue by petepall** [Luxcium/pop-n-lock-theme-vscode#75]
Hi,

Is there an option to reduce the transparency of the command pallet and other transparent elements?
I have a hard time to distinguish some of the texts due to this transparency.

Version in use: v3.18.5
Theme: TSA/ASD version.

![Screenshot from 2020-07-05 15-38-36](https://user-images.githubusercontent.com/42099752/86534058-c9224800-bed5-11ea-9218-ae9e262e85a4.png)

**Comment by Luxcium** [comment]
I will publish  the fix to this bug later today or tomorrow

**Comment by Luxcium** [comment]
![Screenshot_20200715_034111](https://user-images.githubusercontent.com/42672814/87517625-1b3d3900-c64d-11ea-9f79-3f1e0ab5cf69.png)

**Comment by Luxcium** [comment]
![Screenshot_20200715_034250](https://user-images.githubusercontent.com/42672814/87517748-4aec4100-c64d-11ea-9fb1-65716e66f8a3.png)

**Comment by Luxcium** [comment]
updated in version 3.29 and new curent version is now 3.30.0
