### ISSUE TITLE
Emojis on Extension Title

### ISSUE THREAD

**Issue by kodaman2** [Luxcium/pop-n-lock-theme-vscode#79]
Hi awesome theme! A minor issue. I am using a day/night extension to toggle between dark and light themes. A high percentage if not most themes have an easy name to type in my settings. This one however has an emoji at the end which makes it difficult to put in my settings.

I had to go to your homepage of the plugin, and copy the emoji as I had no idea how to type it in. Minor issue no deal breaker.

**Comment by Luxcium** [comment]
It is buried at the bottom of the readme page and it is also not in direct relationship with this issue but one can infer from it the solution to this problem «maybe»  the error described is *not* related to this issue but the solution may be useful somehow:

**If you have an error: `🚫Cannot read property 'id'` of undefined Just go in config.json file remove the `"workbench.colorTheme"` then reload vscode and reinstall `Pop N' Lock Theme by Luxcium ✨`**

**Comment by Luxcium** [comment]
or maybe more useful and still not directly related this part of the read me: 

### **Make sure to set encoding of your config file to utf8**

```JSONC
{
  "workbench.colorTheme": "Pop N' Lock Theme by Luxcium ✨",

  "files.encoding": "utf8",
  "files.autoGuessEncoding": false,

  "workbench.editor.highlightModifiedTabs": true,

  "workbench.iconTheme": "material-icon-theme",
  "material-icon-theme.showReloadMessage": true,
  "editor.fontFamily": "Fira Code iScript, Fira Code",
  "editor.fontLigatures": true,
  "editor.fontSize": 14,
  "editor.suggestFontSize": 16
}
```

> _The name of the theme contain emoticon and encoding must be set to "utf8"_
