### ISSUE TITLE
I keep being mentioned in commit messages here

### ISSUE THREAD

**Issue by MichealPearce** [Luxcium/pop-n-lock-theme-vscode#95]
Hi @Luxcium it seems you keep @'ing me in your commit messages (which look well written!). I'm almost entirely certain this is by mistake though as in the messages you refer often to talking to me about something but we've never formally met before.

I couldn't find another way to message you which is why I'm making this issue. If you could hold off on @'ing in your commits, that would be sweet! Tanka tanka

**Comment by Luxcium** [comment]
Can you give me a commit as an example?
