### ISSUE TITLE
need help with comment colors

### ISSUE THREAD

**Issue by hakancangunerli** [Luxcium/pop-n-lock-theme-vscode#98]
i'm sorry i've to add it as an issue here, but i can't seem to find how to change the comments default color of purple, i checked SO and they said  write like so:

"editor.tokenColorCustomizations":{
    "[Pop N' Lock Theme by Luxcium ✨]": {
        "comments": "#FFFFFF"
    }
    },

but this doesn't change the color. i'm probably at fault here, but could you please tell me the tag so i can change it?

**Comment by Luxcium** [comment]
![Screenshot_20211003_061436](https://user-images.githubusercontent.com/42672814/135749277-3477202b-f25b-4a1d-bd4f-fad6ad27183a.png)
![Screenshot_20211003_061540](https://user-images.githubusercontent.com/42672814/135749314-01aec475-49fa-4f15-9df3-df7840ac62cd.png)
![Screenshot_20211003_061524](https://user-images.githubusercontent.com/42672814/135749315-bcc34dbd-1902-45bc-b3f5-1719b81e87d4.png)
![Screenshot_20211003_061516](https://user-images.githubusercontent.com/42672814/135749316-4d6f4932-2eea-4a13-9a04-37da51f78c40.png)

**Comment by Luxcium** [comment]
```
textmate scopes :  punctuation.definition.comment.jscomment.block.jssource.js
textmate scopes :  punctuation.definition.comment.js comment.line.double-slash.js source.js
```
```
textmate scopes :  comment.block.js source.js
textmate scopes :  comment.line.double-slash.js source.js
```

**Comment by Luxcium** [comment]
**Font style of the rule: 'italic', 'bold' or 'underline' or a combination. The empty string unsets inherited settings.**
```
  "editor.tokenColorCustomizations": {
    "[Pop N' Lock Theme by Luxcium ✨]": {
      "comments": "#FFFFFF",
      "textMateRules": [
        {
          "scope": "comment.block",
          "settings": {
            "foreground": "#FFFFFF",
            "fontStyle": ""
          }
        },
        {
          "scope": "comment.line.double-slash",
          "settings": {
            "foreground": "#FFFFFF",
            "fontStyle": ""
          }
        },
        {
          "scope": "punctuation.definition.comment.jscomment.block.jssource.js source.js",
          "settings": {
            "foreground": "#FFFFFF",
            "fontStyle": ""
          }
        },
        {
          "scope": "punctuation.definition.comment.js comment.line.double-slash.js source.js",
          "settings": {
            "foreground": "#FFFFFF",
            "fontStyle": ""
          }
        },
      ]
    }
  },
```
![Screenshot_20211003_063446](https://user-images.githubusercontent.com/42672814/135749913-acb49e5f-bab7-4938-9630-d2edca6bedde.png)

**Comment by Luxcium** [comment]
**I am unable to change the colour of the comment punctuation**

**Comment by hakancangunerli** [comment]
you're a legend, thank you so much!
